name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'         # changed from '1.7'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: Automation\Automation
      run: mvn clean install

    - name: Run tests
      working-directory: Automation\Automation
      run: mvn test